# Generated by Django 4.1.5 on 2023-01-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("InfoPage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Parent",
        ),
    ]
