# Generated by Django 4.1.5 on 2023-01-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="current_students",
            field=models.JSONField(default=""),
        ),
        migrations.AddField(
            model_name="signup",
            name="description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AddField(
            model_name="signup",
            name="max_students",
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name="signup",
            name="name",
            field=models.TextField(default="Unamed"),
        ),
        migrations.AddField(
            model_name="signup",
            name="restrictions",
            field=models.JSONField(default=""),
        ),
        migrations.AddField(
            model_name="signup",
            name="tags",
            field=models.JSONField(default=""),
        ),
    ]
