# Generated by Django 4.1.5 on 2023-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentApp", "0002_signup_current_students_signup_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="current_students",
            field=models.JSONField(default=False),
        ),
        migrations.AlterField(
            model_name="signup",
            name="restrictions",
            field=models.JSONField(default=False),
        ),
        migrations.AlterField(
            model_name="signup",
            name="tags",
            field=models.JSONField(default=False),
        ),
    ]
