# Generated by Django 4.1.5 on 2023-01-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentApp", "0003_alter_signup_current_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="current_students",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="signup",
            name="restrictions",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="signup",
            name="tags",
            field=models.JSONField(default=dict),
        ),
    ]
