# Generated by Django 4.1.5 on 2023-01-19 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("studentApp", "0004_alter_signup_current_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
